from flask import Flask, request, jsonify
import requests
import base64
import os

app = Flask(name)

# Imgur API Client ID
IMGUR_CLIENT_ID = "YOUR_IMGUR_CLIENT_ID"

@app.route("/upload", methods=["POST"])
def upload_image():
    """
    Endpoint to handle the upload of a Base64-encoded image, 
    upload it to Imgur, and generate a Twitter share link.
    """
    try:
        # Get the Base64 image from the request
        data = request.json
        image_base64 = data.get("image_base64")
        if not image_base64:
            return jsonify({"error": "No image provided"}), 400

        # Decode Base64 data
        image_data = base64.b64decode(image_base64)

        # Upload the image to Imgur
        url = "https://api.imgur.com/3/image"
        headers = {"Authorization": f"Client-ID {IMGUR_CLIENT_ID}"}
        response = requests.post(url, headers=headers, files={"image": image_data})

        if response.status_code == 200:
            imgur_url = response.json()["data"]["link"]

            # Create Twitter share link
            twitter_url = create_twitter_share_link(
                imgur_url,
                "Check out this amazing image generated by AI! #AIArt #DigitalArt"
            )
            return jsonify({"imgur_url": imgur_url, "twitter_url": twitter_url}), 200
        else:
            return jsonify({"error": "Failed to upload to Imgur", "details": response.json()}), 500
    except Exception as e:
        return jsonify({"error": str(e)}), 500

def create_twitter_share_link(imgur_url, text):
    """
    Generate a Twitter share link with the Imgur image URL and custom text.
    """
    base_url = "https://twitter.com/intent/tweet"
    hashtags = "AIArt,DigitalArt"
    tweet_text = text.replace(" ", "%20")
    return f"{base_url}?text={tweet_text}&url={imgur_url}&hashtags={hashtags}"

if name == "main":
    app.run(debug=True)