import { useState } from "react";

export default function Home() {
    const [generatedImage, setGeneratedImage] = useState(null); // AI-generated image (Base64 format)
    const [twitterLink, setTwitterLink] = useState(null); // Twitter share link
    const [loading, setLoading] = useState(false);

    const handleGenerateImage = async () => {
        /**
         * Simulate AI image generation.
         * In a real scenario, replace this with an API call to your AI service.
         */
        const fakeBase64Image =
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA"; // Replace with actual generated Base64 image
        setGeneratedImage(fakeBase64Image);
    };

    const handleShare = async () => {
        if (!generatedImage) return alert("Please generate an image first!");
        setLoading(true);

        // Extract Base64 data without the prefix
        const base64Data = generatedImage.split(",")[1];

        const response = await fetch("http://localhost:5000/upload", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ image_base64: base64Data }),
        });

        if (response.ok) {
            const { twitter_url } = await response.json();
            setTwitterLink(twitter_url);
        } else {
            alert("Failed to share the image.");
        }
        setLoading(false);
    };

    return (
        <div style={{ padding: "20px" }}>
            <h1>AI Image Generator</h1>

            {/* Generate Image */}
            <button onClick={handleGenerateImage}>Generate Image</button>
            {generatedImage && (
                <div>
                    <img
                        src={generatedImage}
                        alt="Generated by AI"
                        style={{ width: "300px", margin: "20px 0" }}
                    />
                </div>
            )}

            {/* Share Image */}
            <button onClick={handleShare} disabled={loading}>
                {loading ? "Sharing..." : "Share on Twitter"}
            </button>

            {/* Twitter Share Link */}
            {twitterLink && (
                <div style={{ marginTop: "20px" }}>
                    <a
                        href={twitterLink}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Share this image on Twitter
                    </a>
                </div>
            )}
        </div>
    );
}
